/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.Aviary;
import persistence.PersistAviary;

/**
 *
 * @author Eduardo Czpla
 */
public class ViewAviaryNewInternal extends javax.swing.JInternalFrame {

    private Aviary aviary;
    private PersistAviary persistAviary;
    
    /**
     * Creates new form ViewAviaryInternal
     */
    public ViewAviaryNewInternal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAviaryStreet = new javax.swing.JTextField();
        txtAviaryNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAviarySave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtAviarySize = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAviaryName = new javax.swing.JTextField();
        txtAviaryCity = new javax.swing.JTextField();
        txtAviaryState = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        txtAviaryStreet.setToolTipText("Digite a rua...");

        txtAviaryNumber.setToolTipText("Digite o número...");

        jLabel1.setText("Nome:");

        jLabel2.setText("Cidade:");

        jLabel3.setText("Estado:");

        jLabel4.setText("Rua:");

        btnAviarySave.setText("Salvar");
        btnAviarySave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAviarySaveActionPerformed(evt);
            }
        });

        jLabel5.setText("Número:");

        txtAviarySize.setToolTipText("Digite o tamanho...");

        jLabel6.setText("Tamanho:");

        txtAviaryName.setToolTipText("");
        txtAviaryName.setName(""); // NOI18N

        txtAviaryCity.setToolTipText("Digite a cidade...");
        txtAviaryCity.setName(""); // NOI18N

        txtAviaryState.setToolTipText("Digite o estado...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAviarySave, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtAviaryStreet)
                        .addComponent(txtAviaryState)
                        .addComponent(txtAviaryName)
                        .addComponent(txtAviaryCity, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtAviarySize, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtAviaryNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAviaryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAviaryCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAviaryState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAviaryStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAviaryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAviarySize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(35, 35, 35)
                .addComponent(btnAviarySave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        setBounds(300, 100, 467, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAviarySaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAviarySaveActionPerformed
        try {
            aviary = new Aviary();
            persistAviary = new PersistAviary();

            aviary.setName(txtAviaryName.getText());
            aviary.setCity(txtAviaryCity.getText());
            aviary.setState(txtAviaryState.getText());
            aviary.setStreet(txtAviaryStreet.getText());
            aviary.setNumber(Integer.parseInt(txtAviaryNumber.getText()));
            aviary.setSize(Integer.parseInt(txtAviarySize.getText()));

            boolean result = persistAviary.store(aviary);

            if(result == true) {
                JOptionPane.showMessageDialog(null, "Aviário salvo com sucesso.", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro ao salvar o aviário.", "ERRO", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAviarySaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAviarySave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAviaryCity;
    private javax.swing.JTextField txtAviaryName;
    private javax.swing.JTextField txtAviaryNumber;
    private javax.swing.JTextField txtAviarySize;
    private javax.swing.JTextField txtAviaryState;
    private javax.swing.JTextField txtAviaryStreet;
    // End of variables declaration//GEN-END:variables
}
